CREATE ROLE connectorsql WITH LOGIN PASSWORD 'connectorsql';

GRANT ALL PRIVILEGES ON DATABASE prodchain TO connectorsql;

-- Dar permisos sobre el esquema público
GRANT USAGE ON SCHEMA public TO connectorsql;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO connectorsql;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO connectorsql;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO connectorsql;


ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO connectorsql;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO connectorsql;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO connectorsql;


